name: CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: arduino/setup-protoc@v2
    
    - name: Build Bicycle
      run: cargo build --verbose
    
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
