name: Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: arduino/setup-protoc@v2

    ## TODO: this should only be to build the database with a fully featured
    ## TODO: protobuf file schema, run the server, and test all of the individual
    ## TODO: endpoints, and monitor performance characteristics with changes.
    - name: Build Bicycle
      run: cargo build --verbose
    - name: Build Plugin
      run: cd ./plugin && cargo build --verbose
    
concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
