name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  job:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - uses: arduino/setup-protoc@v2
    - name: Build
      run: cargo build --verbose
    - name: Tests
      run: cargo test --verbose
    - name: Benchmark
      run: cargo bench --verbose
